[package]
name = "aligned_nearest_neighbor"
version = "1.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
bio = { version = "0.42" }
rstest = { version = "0.26" }
rayon = { version = "1.11" }
indicatif = { version = "0.18", features = ["rayon"] }
